/*
 * This source file was generated by the Gradle 'init' task
 */
package tpjava;

import javax.swing.SwingUtilities;

import tpjava.controller.MonController;
import tpjava.model.MonModel;
import tpjava.vue.MonVue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            MonModel model = new MonModel();
            MonVue vue = new MonVue(model, 30);
            MonController controller = new MonController(model, vue);
            vue.setVisible(true);
        });
    }
}
