/*
 * This source file was generated by the Gradle 'init' task
 */
package Tetris;

import Tetris.VueController.GeneralScreen;

public class App {
    public static void main(String[] args) {
        if (args.length > 0) {
            if (args[0].equals("-debug")) {
                System.out.println("Debug mode activated");
                if (args.length > 1) {
                    System.out.println("Debug mode activated with argument: " + args[1]);
                    new GeneralScreen(true, Integer.parseInt(args[1]));
                } else {
                    new GeneralScreen(true, 0);
                }
            } else {
                System.out.println("Invalid argument: " + args[0]);
                System.out.println("Usage: java -jar Tetris.jar [-debug [port]]");
                System.exit(1);
            }
        } else {
            new GeneralScreen(false, 0);
        }
    }
}
