/*
 * This source file was generated by the Gradle 'init' task
 */
package Tetris;

import Tetris.vue.GeneralScreen;

public class App {
    public static void main(String[] args) {
        new GeneralScreen();
    }
}
